import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from './Components/Navbar';
import Container from './Components/Container';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-950">
        <Navbar />
        <Container>{children}</Container>
      </body>
    </html>
  );
}
